# Generated by Django 4.2.9 on 2024-02-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('newshub', '0003_comments_is_parent_comments_parent_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentonbranch', to='branches.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentonleaf', to='branches.leaf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentonrating', to='branches.rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votingonbranch', to='branches.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votingonleaf', to='branches.leaf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votingonrating', to='branches.rating'),
            preserve_default=False,
        ),
    ]
