# Generated by Django 4.2.9 on 2024-02-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('newshub', '0004_comments_branch_comments_leaf_comments_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='branch',
        ),
        migrations.AlterField(
            model_name='comments',
            name='leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentonleaf', to='branches.leaf'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='news_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentonrating', to='branches.rating'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votingonbranch', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commnt_voteing', to='newshub.comments'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votingonleaf', to='branches.leaf'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votingonrating', to='branches.rating'),
        ),
    ]
