# Generated by Django 4.2.9 on 2024-02-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newshub', '0005_remove_comments_branch_alter_comments_leaf_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together=set(),
        ),
    ]
